In [1]:
import pandas as pd
import numpy as np

In [2]:
dados = {'nome': ['Argentina','Brasil','França','Itália', 'Reino Unido'],
'continente': ['América','América','Europa','Europa','Europa'],
'extensao':[2780,8511,644,301,244],
'corVerde': [0,1,0,1,0]}
siglas = ['AR','BR','FR','IT','UK']

In [3]:
paises = pd.DataFrame(data= dados, index = siglas)
paises

           nome continente  extensao  corVerde
AR    Argentina    América      2780         0
BR       Brasil    América      8511         1
FR       França     Europa       644         0
IT       Itália     Europa       301         1
UK  Reino Unido     Europa       244         0

In [ ]:
paises.shape[0] #Número de linhas axis = 0

5

In [ ]:
paises.shape[1] #número de colunas axis = 1

4

- No vocabulário adotado pela pandas, o termo 'index' é sempre utilizado para índices das linhas
- Enquanto o termo 'column' é utilizado para os índices das colunas.

In [ ]:
paises.index #Lista com os índices

Index(['AR', 'BR', 'FR', 'IT', 'UK'], dtype='object')

In [ ]:
paises.columns #Lista com os rótulos das colunas

Index(['nome', 'continente', 'extensao', 'corVerde'], dtype='object')

In [ ]:
paises.dtypes #dtipos dos elementos das colunas

nome          object
continente    object
extensao       int64
corVerde       int64
dtype: object

- Pandas disponibiliza quatro diferentes métodos para esta operação: 
iloc() , iat() , loc() e at(). 
- Os dois primeiros são utilizados para indexação baseada na posição da linha (número inteiro), enquanto os dois últimos são para acessar linhas através de seus rótulos.

In [ ]:
paises.iloc[1][0] #Retorna o valor que está na célula da linha 1 e da coluna 0 da serie

/tmp/ipykernel_23413/2666814518.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  paises.iloc[1][0]

'Brasil'

In [11]:
paises.iat[1,0] #Retorna o valor que está na célula da linha 1 e da coluna 0 da serie

'Brasil'

In [ ]:
paises.iloc[3]['corVerde'] #Retorna o valor que está na célula 3 e da coluna denominada corVerde

np.int64(1)

In [ ]:
paises.loc['IT'][1] #Retorna o valor da céclula da linha do índice denominado IT e coluna 1

/tmp/ipykernel_23413/1506262804.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  paises.loc['IT'][1]

'Europa'

In [ ]:
paises.at['FR', 'nome'] #Retorna o valor da célula da linha do índice denominado FR e da coluna denominada nome

'França'

- O fatiamento de DataFrames pode ser realizado com o uso dos métodos iloc() (por posição) e loc() (por rótulo).
- Em todos os casos o resultado será retornado em objeto do tipo Series.

In [ ]:
paises['extensao'] #Retorna toda a coluna de nome 'extensao'

AR    2780
BR    8511
FR     644
IT     301
UK     244
Name: extensao, dtype: int64

In [ ]:
paises.corVerde #outra forma para retornar a coluna de nome corVerde

AR    0
BR    1
FR    0
IT    1
UK    0
Name: corVerde, dtype: int64

In [17]:
paises.loc['BR'] #Retorna a linha inteira associada ao índice denominado BR

nome           Brasil
continente    América
extensao         8511
corVerde            1
Name: BR, dtype: object

In [18]:
paises.iloc[2] #Retorna a linha inteira que ocupa a posição de índice 2

nome          França
continente    Europa
extensao         644
corVerde           0
Name: FR, dtype: object

- As "fatias" de linhas e colunas desejadas devem ser definidas dentro de colchetes [ ] , com o uso do operador dois-pontos ( : ) e separadas por vírgula ( , ). Primeiro deve-se definir a fatia de linhas e depois a de colunas.

In [19]:
paises.iloc[:3, :2] #retorna uma fatia contendo as três primeiras linhas e duas primeiras colunas. (inclusiva:exclusiva)

         nome continente
AR  Argentina    América
BR     Brasil    América
FR     França     Europa

In [20]:
paises.loc[['BR', 'IT'], 'corVerde'] #para as linhas rotuladas com 'BR' e 'IT' , retorna o valor armazenado na coluna corVerde.

BR    1
IT    1
Name: corVerde, dtype: int64

In [21]:
paises.iloc[-2:, 1:3] #retorna uma fatia contendo as duas últimas linhas e as colunas de índice 1 e 2.

   continente  extensao
IT     Europa       301
UK     Europa       244

- A técnica para fatiar DataFrames é muito similar à que é empregada no fatiamento de Series. 
- O que muda é apenas o fato de que você precisa especificar uma fatia para linhas e outra para colunas.

In [ ]:
'BR' in paises.index #Confere se a serie possui algum dos índices denominados BR

True

In [23]:
'US' in paises.index

False

In [ ]:
'corVerde' in paises.columns #Confere se a serie possui alguma das colunas denominadas corVerde

True

In [ ]:
paises['nome'].isin(['Brasil']) #Testa se um rótulo faz parte da coluna

AR    False
BR     True
FR    False
IT    False
UK    False
Name: nome, dtype: bool

In [ ]:
paises.loc['JP'] = {'nome': 'Japão',
                    'continente': 'Ásia',
                    'extensao': 372,
                    'corVerde': 0
                    }
#Foi inserido o país Japão na serie

In [27]:
paises.at['BR', 'extensao'] = 8512 #Foi alterada a extensão do Brasil

In [28]:
paises = paises.drop(['AR', 'UK']) #Foi removida a Argentina e o Reino Unido

In [29]:
paises

      nome continente  extensao  corVerde
BR  Brasil    América      8512         1
FR  França     Europa       644         0
IT  Itália     Europa       301         1
JP   Japão       Ásia       372         0

- Para inserir o Japão, bastou indicar os dados desse país em um dicionário e realizar a atribuição com o uso do método 'loc()' . Caso o DataFrame não possuísse rótulos de linha, seria preciso utilizar o método 'iloc()' com o índice da linha a ser inserida.
- Para alterar uma célula, no caso, a extensão do Brasil, utilizou-se um comando de atribuição simples que empregou o método 'at()' com a indicação dos rótulos de linha e coluna da célula a ser alterada. Caso o DataFrame não possuísse rótulos de linha, seria preciso utilizar o método 'iat()' com o índice da linha a ser alterada.
- Por fim, para remover linhas, basta utilizar o método 'drop()' indicando a lista de rótulos de linha a serem removidos.

Podemos realizar a leitura de arquivos CSV (comma-separated values — valores separados por vírgula) e de outros tipos de arquivos baseados em caracteres delimitadores utilizando o método 'read_csv()'.

In [31]:
paises = pd.read_csv('paises.csv', index_col = 'sigla')
print(paises)

              nome continente  extensao  corVerde
sigla
AR       Argentina    América      2780         0
BR          Brasil    América      8511         1
FR          França     Europa       644         0
IT          Itália     Europa       301         1
UK     Reino Unido     Europa       244         0

- O método 'read_csv()' é extremamente flexível, possuindo uma série de parâmetros que podem ser utilizados para permitir a importação de arquivos CSV.
- Os principais parâmetros são relacionados e explicados a seguir:
    - sep : caractere ou expressão regular utilizada para separar campos em cada linha;
    - skiprows : número de linhas no início do arquivo que devem ser ignoradas;
    - skip_footer : número de linhas no final do arquivo que devem ser ignoradas;
    - encoding : padrão de codificação do arquivo. A codificação default da pandas é utf-8. Se o seu arquivo estiver codificado no formato ANSI, você deverá utilizar encoding='ansi';
    - header : número da linha que contém o cabeçalho (default=0). Se não houver cabeçalho, deve-se especificar header=None ou passar uma lista de nomes através do parâmetro names ;
    - names : permite especificar uma lista de nomes para as colunas;
    - index_col : permite que uma das colunas seja transformada em índice de linhas;
    - na_values : sequência de valores que deverão ser substituídos por NA . Útil para transformação de dados;
    - thousands : definição do separador de milhar, por exemplo . ou , ;
    - squeeze : caso o arquivo CSV possua apenas uma coluna, é possível fazer com que ele seja importado para uma Series em vez de um DataFrame, bastando para isso especificar squeeze=True .

In [32]:
notas = pd.read_csv('notas.csv', sep=';', names=['matricula', 'nota1', 'nota2'])
print(notas)

  matricula  nota1  nota2
0  M0012017    9.8    9.5
1  M0022017    5.3    4.1
2  M0032017    2.5    8.0
3  M0042017    7.5    7.5

- O parâmetro 'sep' foi utilizado para definir ';' como separador, enquanto 'names' foi empregado para definir os cabeçalhos das
colunas. 
- Desta vez, não utilizamos o parâmetro 'index_col' e, por consequência, os índices de linha foram definidos como números inteiros 
- Para que fosse possível colocar matrículas como índices de linha, bastaria ter feito: index_col='matricula' .

In [ ]:
gols = pd.read_csv('gols.txt', sep=' ', index_col=0) #O separador (sep) é espaço em branco e que a primera coluna do arquivo deverá ser usada para formar os rótulos do índice
gols.squeeze() #Tranforma o DataFrme que o read_csv por padrão retorna em serie

dia
05/06/2019    1
09/06/2019    0
16/06/2019    5
19/06/2019    2
23/06/2019    1
27/06/2019    3
30/06/2019    0
Name: gols, dtype: int64

In [36]:
gols.index = pd.to_datetime(gols.index, format='%d/%m/%Y')
print(gols)

            gols
dia
2019-06-05     1
2019-06-09     0
2019-06-16     5
2019-06-19     2
2019-06-23     1
2019-06-27     3
2019-06-30     0

In [ ]:
capitais = pd.read_excel('capitais.xlsx') #Importando arquivos de excel para formar um DataFrame
print(capitais)

            capital   região  população
0   Belém            Sudeste    1446042
1   Belo Horizonte   Sudeste    2513451
2   Boa Vista          Norte     326419
3   Curitiba             Sul    1893977
4   Florianópolis        Sul     477798
5   Macapá             Norte     465495
6   Manaus             Norte    2094391
7   Palmas             Norte     279856
8   Porto Alegre         Sul    1481019
9   Porto Velho        Norte     511219
10  Rio Branco         Norte     377057
11  São Paulo        Sudeste   12038175
12  Rio de Janeiro   Sudeste    6498837
13  Vitória          Sudeste     359555

- JSON (JavaScript Object Notation) é um modelo para armazenamento e transmissão de informações no formato texto.
- Apesar de muito simples, é o mais utilizado por aplicações Web devido à sua capacidade de estruturar informações de forma compacta e autodescritiva.

In [38]:
import json

In [ ]:
with open('notas.json') as f: #Importa o arquivo JSON para a memória
    notas = json.load(f)

In [ ]:
notas = pd.DataFrame(notas, columns=['matricula', 'notas']) #Transfere as informações para um DataFrame

In [41]:
print(notas)

  matricula       notas
0  M0012017  [9.8, 9.5]
1  M0022017  [5.3, 4.1]
2  M0032017  [2.5, 8.0]
3  M0042017  [7.5, 7.5]

In [42]:
dados = {'codigo': [1001,1002,1003,1004,1005],
'nome': ['Leite','Café','Biscoito','Chá',
'Torradas']
}

produtos = pd.DataFrame(dados)

In [ ]:
produtos.to_csv('produtos.csv', sep='\t', index=False) #Salva o seu conteúdo para um arquivo

- Nos parâmetros do método 'to_csv()' , a tabulação '\t' foi adotada como caractere delimitador (parâmetro 'sep' ) e a opção 'index=False' foi utilizada para evitar que os rótulos dos índices (números inteiros) fossem gravados no arquivo.

In [47]:
flags = pd.read_csv('flags.csv')
flags.head()

,name,landmass,zone,area,population,language,religion,bars,stripes,colours,...,saltires,quarters,sunstars,crescent,triangle,icon,animate,text,topleft,botright
0,Afghanistan,5,1,648,16,10,2,0,3,5,...,0,0,1,0,0,1,0,0,black,green
1,Albania,3,1,29,3,6,6,0,0,3,...,0,0,1,0,0,0,1,0,red,red
2,Algeria,4,1,2388,20,8,2,2,0,3,...,0,0,1,1,0,0,0,0,green,white
3,American-Samoa,6,3,0,0,1,1,0,0,5,...,0,0,0,0,1,1,1,0,blue,red
4,Andorra,3,1,0,0,6,0,3,0,3,...,0,0,0,0,0,0,0,0,blue,red

In [46]:
verde = flags['green']
amarelo = flags['gold']
azul = flags['blue']
branco = flags['white']
soma = verde + amarelo + azul + branco
tem_todas = (soma==4)

print(flags[tem_todas.values]['name'])

17                       Belize
19                      Bermuda
23                       Brazil
24         British-Virgin-Isles
26                     Bulgaria
33               Cayman-Islands
34     Central-African-Republic
48                     Dominica
56           Falklands-Malvinas
57                         Fiji
71                         Guam
78                    Hong-Kong
116                  Montserrat
135                     Parguay
139                    Portugal
142                     Romania
151             Soloman-Islands
158                   St-Helena
161                  St-Vincent
176         Turks-Cocos-Islands
182             US-Virgin-Isles
187                   Venezuela
Name: name, dtype: object