In [1]:
import pandas as pd
import numpy as np

-> Cada linha é utilizada para armazenar um objeto da base de dados enquanto as colunas são utilizadas para representar os atributos que descrevem as características dos objetos.

-> Tipo de dado numérico é um atributo que pode armazenar uma ampla gama de valores numéricos sobre os quais podemos executar operações como soma, subtração, obtenção de valor médio etc.
    -> Possui dois atributos:
        -> do tipo discreto: aquele que pode assumir um conjunto finito ou infinito contável de valores (int64)
        -> do tipo contínuo: qualquer atributo numérico que não seja discreto (float64)

-> Tipo de dado categórico
    -> Possui dois atributos
        -> nominal: cujos níveis não possuem nenhum tipo de ordenação especial. Por exemplo: sexo masculino não é superior ou inferior ao sexo faminino
        -> ordinal: possuem ordem natural de nível nos seus dados. Por exemplo: ensino superior está em um nível acima do ensino médio que está um nível acima do fundamental. 

-> Nos DataFrames, os atributos categóricos, sejam ordinais ou nominais, são normalmente armazenados em colunas cujo dtype é object

-> Entretanto, também é possível estruturar dados categóricos em colunas int64 , bastando para isso mapear as categorias para conjuntos de códigos. Por exemplo, no caso do atributo escolaridade , os códigos 1, 2, 3 e 4 poderiam ser utilizados para representar as categorias "fundamental", "médio", "superior" e "pós-graduação", respectivamente.

-> Identificar corretamente os diferentes tipos de atributos de uma base de dados é uma tarefa importante. Isso porque existem medidas e operações diferentes para estudar cada um. Por exemplo, faz sentido utilizar a medida conhecida como moda (valor mais frequente) para estudar atributos categóricos e discretos, mas ela não ajuda muito no estudo de um atributo contínuo.

In [ ]:
dados = {"renda": [6.46, 1.50, 0.00, 2.57, 9.90, 6.22], #tipo de atributo numérico continuo
"empregos": [1,1,0,1,2,3], ##tipo de atributo numérico discreto
"sexo": ["F","M","F","M","M","F"], #tipo de atributo categórico nominal
"escolaridade": ["pós-graduação","fundamental","médio","médio", "superior","médio"] #tipo de atributo categórico ordinal
}

pme = pd.DataFrame(dados)

In [3]:
pme.dtypes

renda           float64
empregos          int64
sexo             object
escolaridade     object
dtype: object

-> Um objeto (linha do DataFrame) pode também ser chamado de observação, instância, exemplo, registro, tupla ou data point. 
-> Por sua vez, um atributo (coluna do DataFrame) pode também ser chamado de variável, feature, dimensão ou data field.

###Medidas de tendência central

- Uma medida de tendência central é aquela capaz de representar o que é médio ou típico do conjunto de dados.

- Neste tópico, serão apresentadas três medidas de tendência central: 
    - média (Trata-se da soma de cada valor do conjunto de dados, dividida pelo número de observações do conjunto). Tipos de atributo contínuo e discreto
    - mediana (A ideia desta medida é separar a distribuição em duas partes iguais. A mediana corresponderá ao ponto do meio. Caso o conjunto de dados possua um número par de valores, você precisará somar os dois "casos médios" e dividir o resultado por dois. Por exemplo, no conjunto de dados {3, 4, 8, 11} a mediana é obtida por (4+8) / 2 = 6.). Tipos de atributo contínuo e discreto 
    
    - moda (consiste no valor mais frequente em uma distribuição.). Tipos de atributo discreto, nominal e ordinal

- Na pandas, os métodos mean() , median() e mode() são utilizados para calcular, respectivamente, os valores da média, mediana e moda.

In [4]:
dados = {"jogador": ["Marcelo",
"Pedro",
"Marcelo",
"Adriano",
"Mauro",
"Pedro",
"Marcelo"],
"infracao": ["FALTA VIOLENTA",
"RECLAMACAO",
"FALTA COMUM",
"RECLAMACAO",
"FALTA COMUM",
"FALTA VIOLENTA",
"RECLAMACAO"],
"punicao":[4,1,3,2,4,4,2]
}

df = pd.DataFrame(dados)

In [5]:
df

   jogador        infracao  punicao
0  Marcelo  FALTA VIOLENTA        4
1    Pedro      RECLAMACAO        1
2  Marcelo     FALTA COMUM        3
3  Adriano      RECLAMACAO        2
4    Mauro     FALTA COMUM        4
5    Pedro  FALTA VIOLENTA        4
6  Marcelo      RECLAMACAO        2

In [ ]:
#Calcular a medidas das tendência central
df['punicao'].mean() #Média das punições dos jogadores

np.float64(2.857142857142857)

In [ ]:
df['punicao'].median() #Mediana das punições dos jogadores

3.0

In [ ]:
df['punicao'].mode() #Moda das punições dos jogadores

0    4
Name: punicao, dtype: int64

-> O método mode() sempre retorna uma Series em vez de um número. Isso porque uma distribuição pode ser unimodal (possui uma moda), bimodal (possui duas modas) ou multimodal (apresenta várias modas).

###Medidas de variabilidade

- Como acabamos de mostrar, média, mediana e moda são medidas que têm por objetivo sintetizar em um único número o que é típico (ou médio) em um conjunto de dados. Porém, em muitas situações práticas estas medidas conseguem fornecer apenas um quadro incompleto dos seus dados.
- Três medidas deste tipo:
    - Amplitude (é uma medida rápida da variabilidade). Ela consiste na diferença entre o mais alto e o mais baixo valor de um determinado conjunto de dados. A amplitude tem a vantagem de ser simples e rápida de calcular. Porém, tem a desvantagem de depender apenas de dois valores de toda a distribuição (o menor valor e o maior valor). Por isso, existirá sempre o risco de ela ser influenciada por um único valor extremo e muito diferente dos demais. A solução é adotar medidas que levem em conta todos os valores da distribuição, como é o caso da variância e do desvio padrão. 
    
    - variância realiza a soma dos quadrados dos desvios e divide o resultado por N-1, que corresponde ao número total de scores menos 1. A ideia de elevar ao quadrado é usada somente para eliminar os sinais negativos de alguns desvios. A variância considera todos os valores da distribuição, oferecendo uma vantagem sobre amplitude, que considera somente dois valores. No entanto, um problema associado a esta medida é a sua interpretação difícil. Como os valores dos desvios são elevados ao quadrado, a unidade original de medida acaba sendo alterada. Corrigir esse problema é muito simples: basta utilizar a medida de desvio padrão. 
    
    - Desvio padrão (que consiste na distância de um valor arbitrário ao valor médio de um conjunto de dados). Essa medida corresponde a nada mais do que a raiz quadrada da variância. Ela é usada exatamente para colocar o valor da variabilidade na unidade original. 

- No pandas, podemos calcular a amplitude com o uso dos métodos min() e max() , que obtêm os valores mínimo e máximo de uma distribuição, respectivamente. Já a variância pode ser computada com o uso do método var() , enquanto, para o desvio padrão, utiliza-se o método std() .

In [12]:
dados = {"jogador": ["Marcelo",
"Pedro",
"Marcelo",
"Adriano",
"Mauro",
"Pedro",
"Marcelo"],
"infracao": ["FALTA VIOLENTA",
"RECLAMACAO",
"FALTA COMUM",
"RECLAMACAO",
"FALTA COMUM",
"FALTA VIOLENTA",
"RECLAMACAO"],
"juiz_A": [4,1,3,2,4,4,2],
"juiz_B": [2,1,4,1,1,5,6]
}

df = pd.DataFrame(dados)
df

   jogador        infracao  juiz_A  juiz_B
0  Marcelo  FALTA VIOLENTA       4       2
1    Pedro      RECLAMACAO       1       1
2  Marcelo     FALTA COMUM       3       4
3  Adriano      RECLAMACAO       2       1
4    Mauro     FALTA COMUM       4       1
5    Pedro  FALTA VIOLENTA       4       5
6  Marcelo      RECLAMACAO       2       6

In [13]:
#Calcular as medidas de variabilidades

#Amplitude
df['juiz_A'].max() - df['juiz_A'].min()

3

In [14]:
#Variância
df['juiz_A'].var()

1.476190476190476

In [15]:
#Desvio padrão
df['juiz_A'].std()

1.2149857925879117